export const SEO_KEYWORDS = [
  { keyword: "cómo saber mi tipo de piel", slug: "como-saber-mi-tipo-piel" },
  { keyword: "rutina de skincare para piel grasa", slug: "rutina-skincare-piel-grasa" },
  { keyword: "mejores ingredientes para piel sensible", slug: "mejores-ingredientes-piel-sensible" },
  { keyword: "cómo eliminar puntos negros", slug: "eliminar-puntos-negros" },
  { keyword: "crema hidratante para piel mixta", slug: "crema-hidratante-piel-mixta" },
  { keyword: "protector solar para piel grasa", slug: "protector-solar-piel-grasa" },
  { keyword: "ácido hialurónico beneficios", slug: "acido-hialuronico-beneficios" },
  { keyword: "retinol para principiantes", slug: "retinol-principiantes" },
  { keyword: "diferencia entre piel grasa y deshidratada", slug: "piel-grasa-vs-deshidratada" },
  { keyword: "skincare para hombres", slug: "skincare-hombres" },
  { keyword: "cómo cuidar la piel en verano", slug: "cuidar-piel-verano" },
  { keyword: "cómo cuidar la piel en invierno", slug: "cuidar-piel-invierno" },
  { keyword: "piel seca vs piel deshidratada", slug: "piel-seca-vs-deshidratada" },
  { keyword: "cómo elegir tu rutina de skincare", slug: "elegir-rutina-skincare" },
  { keyword: "ingredientes que debes evitar según tu piel", slug: "ingredientes-evitar-segun-piel" },
  { keyword: "cómo saber si un producto es bueno para tu piel", slug: "saber-si-producto-es-bueno" },
  { keyword: "qué es el pH de la piel", slug: "que-es-ph-piel" },
  { keyword: "cómo mejorar la textura de la piel", slug: "mejorar-textura-piel" },
  { keyword: "cómo reducir los poros abiertos", slug: "reducir-poros-abiertos" },
  { keyword: "cómo eliminar manchas de la piel", slug: "eliminar-manchas-piel" },
  { keyword: "rutina skincare para piel sensible", slug: "rutina-skincare-piel-sensible" },
  { keyword: "crema hidratante para piel grasa", slug: "crema-hidratante-piel-grasa" },
  { keyword: "serum vitamina c beneficios", slug: "serum-vitamina-c-beneficios" },
  { keyword: "cómo eliminar acné rápido", slug: "eliminar-acne-rapido" },
  // 30 new keywords
  { keyword: "niacinamida beneficios para la piel", slug: "niacinamida-beneficios-piel" },
  { keyword: "cómo usar ácido glicólico", slug: "usar-acido-glicolico" },
  { keyword: "skincare después de los 30", slug: "skincare-despues-30" },
  { keyword: "skincare después de los 40", slug: "skincare-despues-40" },
  { keyword: "cómo desinflamar la cara rápido", slug: "desinflamar-cara-rapido" },
  { keyword: "aceite de árbol de té para la piel", slug: "aceite-arbol-te-piel" },
  { keyword: "cómo quitar ojeras naturalmente", slug: "quitar-ojeras-naturalmente" },
  { keyword: "colágeno beneficios para la piel", slug: "colageno-beneficios-piel" },
  { keyword: "cómo prevenir arrugas", slug: "prevenir-arrugas" },
  { keyword: "exfoliante facial casero", slug: "exfoliante-facial-casero" },
  { keyword: "cómo cerrar poros después de limpiar", slug: "cerrar-poros-despues-limpiar" },
  { keyword: "vitamina C serum cómo usar", slug: "vitamina-c-serum-como-usar" },
  { keyword: "cuidado de la piel en embarazo", slug: "cuidado-piel-embarazo" },
  { keyword: "cómo eliminar cicatrices de acné", slug: "eliminar-cicatrices-acne" },
  { keyword: "tónico facial para qué sirve", slug: "tonico-facial-para-que-sirve" },
  { keyword: "mascarilla facial para piel grasa", slug: "mascarilla-facial-piel-grasa" },
  { keyword: "cómo saber si tengo piel sensible", slug: "saber-si-tengo-piel-sensible" },
  { keyword: "agua micelar para qué sirve", slug: "agua-micelar-para-que-sirve" },
  { keyword: "cuidado de la piel masculina rutina", slug: "cuidado-piel-masculina-rutina" },
  { keyword: "skincare vegano y cruelty free", slug: "skincare-vegano-cruelty-free" },
  { keyword: "cómo combatir puntos negros en la nariz", slug: "combatir-puntos-negros-nariz" },
  { keyword: "sérum de retinol mejores opciones", slug: "serum-retinol-mejores-opciones" },
  { keyword: "crema para ojeras y bolsas", slug: "crema-ojeras-bolsas" },
  { keyword: "cómo desmanchar la piel naturalmente", slug: "desmanchar-piel-naturalmente" },
  { keyword: "limpiador facial para piel mixta", slug: "limpiador-facial-piel-mixta" },
  { keyword: "skincare coreano rutina paso a paso", slug: "skincare-coreano-rutina" },
  { keyword: "cómo reparar la barrera cutánea", slug: "reparar-barrera-cutanea" },
  { keyword: "antiedad skincare ingredientes activos", slug: "antiedad-skincare-ingredientes" },
  { keyword: "cómo cuidar la piel con sol directo", slug: "cuidar-piel-sol-directo" },
  { keyword: "productos de skincare para principiantes", slug: "productos-skincare-principiantes" },
]
