export const SEO_KEYWORDS = [
  { keyword: "cómo saber mi tipo de piel", slug: "como-saber-mi-tipo-piel" },
  { keyword: "rutina de skincare para piel grasa", slug: "rutina-skincare-piel-grasa" },
  { keyword: "mejores ingredientes para piel sensible", slug: "mejores-ingredientes-piel-sensible" },
  { keyword: "cómo eliminar puntos negros", slug: "eliminar-puntos-negros" },
  { keyword: "crema hidratante para piel mixta", slug: "crema-hidratante-piel-mixta" },
  { keyword: "protector solar para piel grasa", slug: "protector-solar-piel-grasa" },
  { keyword: "ácido hialurónico beneficios", slug: "acido-hialuronico-beneficios" },
  { keyword: "retinol para principiantes", slug: "retinol-principiantes" },
  { keyword: "diferencia entre piel grasa y deshidratada", slug: "piel-grasa-vs-deshidratada" },
  { keyword: "skincare para hombres", slug: "skincare-hombres" },
  { keyword: "cómo cuidar la piel en verano", slug: "cuidar-piel-verano" },
  { keyword: "cómo cuidar la piel en invierno", slug: "cuidar-piel-invierno" },
  { keyword: "piel seca vs piel deshidratada", slug: "piel-seca-vs-deshidratada" },
  { keyword: "cómo elegir tu rutina de skincare", slug: "elegir-rutina-skincare" },
  { keyword: "ingredientes que debes evitar según tu piel", slug: "ingredientes-evitar-segun-piel" },
  { keyword: "cómo saber si un producto es bueno para tu piel", slug: "saber-si-producto-es-bueno" },
  { keyword: "qué es el pH de la piel", slug: "que-es-ph-piel" },
  { keyword: "cómo mejorar la textura de la piel", slug: "mejorar-textura-piel" },
  { keyword: "cómo reducir los poros abiertos", slug: "reducir-poros-abiertos" },
  { keyword: "cómo eliminar manchas de la piel", slug: "eliminar-manchas-piel" },
  { keyword: "rutina skincare para piel sensible", slug: "rutina-skincare-piel-sensible" },
  { keyword: "crema hidratante para piel grasa", slug: "crema-hidratante-piel-grasa" },
  { keyword: "serum vitamina c beneficios", slug: "serum-vitamina-c-beneficios" },
  { keyword: "cómo eliminar acné rápido", slug: "eliminar-acne-rapido" },
]
