services:
  - type: web
    name: the-serene-lens
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        value: https://the-serene-lens-nuevo.onrender.com
      - key: NEXT_PUBLIC_APP_URL
        value: https://the-serene-lens-nuevo.onrender.com
      - key: GROQ_API_KEY
        sync: false
      - key: QVAPAY_UUID
        sync: false
      - key: QVAPAY_SECRET
        sync: false
      - key: QVAPAY_API_URL
        value: https://api.qvapay.com
      - key: RESEND_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: ROOT_ADMIN_EMAIL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: TELEGRAM_ADMIN_TOKEN
        sync: false
      - key: TELEGRAM_VALIDATOR_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: TRANSFER_ACCOUNT
        sync: false
      - key: TRANSFER_HOLDER
        sync: false
