import "dotenv/config"
import { Pool } from "pg"
import { PrismaPg } from "@prisma/adapter-pg"
import { PrismaClient } from "../src/generated/prisma/client"

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

const guides = [
  // === 10 Principiante (gratis) ===
  {
    title: "Guía básica de cuidado facial",
    slug: "guia-basica-cuidado-facial",
    description: "Aprende los fundamentos del cuidado de la piel: limpieza, hidratación y protección solar. Una guía completa para quienes empiezan desde cero.",
    shortDesc: "Los fundamentos del skincare en una guía completa",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/guia-basica-cuidado-facial.svg",
    fileUrl: "",
  },
  {
    title: "Cómo identificar tu tipo de piel",
    slug: "como-identificar-tipo-piel",
    description: "Descubre si tu piel es grasa, seca, mixta o sensible con tests prácticos y observaciones detalladas. El primer paso para una rutina efectiva.",
    shortDesc: "Identifica tu tipo de piel con tests prácticos",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/como-identificar-tipo-piel.svg",
    fileUrl: "",
  },
  {
    title: "Rutina de 3 pasos para empezar",
    slug: "rutina-3-pasos-empezar",
    description: "Una rutina minimalista pero efectiva: limpiador, hidratante y protector solar. Todo lo que necesitas saber para cuidar tu piel cada día.",
    shortDesc: "Rutina minimalista de limpieza, hidratación y protección",
    category: "rutinas",
    level: "principiante",
    price: 0,
    image: "/guides/rutina-3-pasos-empezar.svg",
    fileUrl: "",
  },
  {
    title: "Limpieza facial: la base del cuidado",
    slug: "limpieza-facial-base-cuidado",
    description: "Todo sobre la limpieza facial: tipos de limpiadores, doble limpieza, frecuencia ideal y errores comunes que dañan tu barrera cutánea.",
    shortDesc: "Guía completa de limpieza facial para principiantes",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/limpieza-facial-base-cuidado.svg",
    fileUrl: "",
  },
  {
    title: "Importancia de la hidratación diaria",
    slug: "importancia-hidratacion-diaria",
    description: "Por qué hidratar tu piel es esencial sin importar tu tipo de piel. Cómo elegir el hidratante adecuado y cuándo aplicarlo.",
    shortDesc: "Todo sobre la hidratación facial y cómo elegir tu crema",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/importancia-hidratacion-diaria.svg",
    fileUrl: "",
  },
  {
    title: "Protección solar: mitos y realidades",
    slug: "proteccion-solar-mitos-realidades",
    description: "Desmiente los mitos más comunes sobre el protector solar. Aprende por qué debes usarlo a diario, incluso en días nublados o en interiores.",
    shortDesc: "Desmiente mitos y aprende la verdad sobre el protector solar",
    category: "proteccion-solar",
    level: "principiante",
    price: 0,
    image: "/guides/proteccion-solar-mitos-realidades.svg",
    fileUrl: "",
  },
  {
    title: "Cómo leer etiquetas de productos",
    slug: "como-leer-etiquetas-productos",
    description: "Aprende a interpretar los ingredientes en las etiquetas de tus productos de skincare. Identifica activos clave, irritantes y lo que realmente funciona.",
    shortDesc: "Descifra las etiquetas y elige mejores productos",
    category: "ingredientes",
    level: "principiante",
    price: 0,
    image: "/guides/como-leer-etiquetas-productos.svg",
    fileUrl: "",
  },
  {
    title: "Tu botiquín de skincare esencial",
    slug: "botiquin-skincare-esencial",
    description: "Los 5 productos básicos que toda persona debería tener en su rutina. Cómo construirlo sin gastar de más y sin complicaciones.",
    shortDesc: "Los 5 productos esenciales para empezar tu rutina",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/botiquin-skincare-esencial.svg",
    fileUrl: "",
  },
  {
    title: "Errores comunes en principiantes",
    slug: "errores-comunes-principiantes",
    description: "Los 10 errores más frecuentes al empezar una rutina de skincare y cómo evitarlos. Desde usar demasiados productos hasta saltarse la protección solar.",
    shortDesc: "Evita los 10 errores más comunes al empezar",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/errores-comunes-principiantes.svg",
    fileUrl: "",
  },
  {
    title: "Cómo elegir tu limpiador facial",
    slug: "como-elegir-limpiador-facial",
    description: "Guía para seleccionar el limpiador perfecto según tu tipo de piel y preocupaciones. Geles, espumas, aceites y bálsamos explicados en detalle.",
    shortDesc: "Selecciona el limpiador ideal para tu tipo de piel",
    category: "cuidado-basico",
    level: "principiante",
    price: 0,
    image: "/guides/como-elegir-limpiador-facial.svg",
    fileUrl: "",
  },

  // === 15 Intermedio ($4.99–$9.99) ===
  {
    title: "Ácidos y exfoliantes: guía completa",
    slug: "acidos-exfoliantes-guia-completa",
    description: "Guía definitiva sobre ácidos exfoliantes: AHA, BHA, PHA. Cómo usarlos, frecuencia ideal, y cómo combinarlos sin irritar tu piel.",
    shortDesc: "AHA, BHA y PHA explicados para una exfoliación segura",
    category: "ingredientes",
    level: "intermedio",
    price: 4.99,
    image: "/guides/acidos-exfoliantes-guia-completa.svg",
    fileUrl: "",
  },
  {
    title: "Ingredientes activos explicados",
    slug: "ingredientes-activos-explicados",
    description: "Enciclopedia visual de los ingredientes activos más importantes: vitamina C, retinol, niacinamida, ácido hialurónico y más. Cómo y cuándo usarlos.",
    shortDesc: "Guía visual de los activos más importantes del skincare",
    category: "ingredientes",
    level: "intermedio",
    price: 5.99,
    image: "/guides/ingredientes-activos-explicados.svg",
    fileUrl: "",
  },
  {
    title: "Cómo construir una rutina anti-edad",
    slug: "rutina-antiedad-40",
    description: "Estrategias respaldadas por la ciencia para prevenir y tratar los signos del envejecimiento. Activos clave, orden de aplicación y productos recomendados.",
    shortDesc: "Estrategias científicas para prevenir el envejecimiento",
    category: "rutinas",
    level: "intermedio",
    price: 6.99,
    image: "/guides/rutina-antiedad-40.svg",
    fileUrl: "",
  },
  {
    title: "Vitamina C: beneficios y aplicación",
    slug: "vitamina-c-beneficios-aplicacion",
    description: "Todo sobre el antioxidante más popular: beneficios, concentraciones ideales, cómo elegir la mejor presentación y cómo incorporarlo a tu rutina.",
    shortDesc: "Guía completa del antioxidante estrella para tu piel",
    category: "ingredientes",
    level: "intermedio",
    price: 4.99,
    image: "/guides/vitamina-c-beneficios-aplicacion.svg",
    fileUrl: "",
  },
  {
    title: "Ácido hialurónico: hidratación profunda",
    slug: "acido-hialuronico-hidratacion-profunda",
    description: "El ingrediente hidratante por excelencia explicado en detalle: cómo funciona, pesos moleculares, cómo aplicarlo para máxima absorción.",
    shortDesc: "Hidratación profunda con ácido hialurónico",
    category: "ingredientes",
    level: "intermedio",
    price: 4.99,
    image: "/guides/acido-hialuronico-hidratacion-profunda.svg",
    fileUrl: "",
  },
  {
    title: "Niacinamida: el ingrediente multipropósito",
    slug: "niacinamida-ingrediente-multiproposito",
    description: "Descubre por qué la niacinamida es uno de los ingredientes más versátiles: poros, manchas, textura y barrera cutánea. Concentraciones y combinaciones.",
    shortDesc: "El ingrediente multitarea que tu rutina necesita",
    category: "ingredientes",
    level: "intermedio",
    price: 4.99,
    image: "/guides/niacinamida-ingrediente-multiproposito.svg",
    fileUrl: "",
  },
  {
    title: "Retinoides: introducción segura",
    slug: "retinoides-introduccion-segura",
    description: "Cómo empezar con retinoides sin irritación. Tipos, concentraciones, frecuencia y el método sándwich para minimizar efectos secundarios.",
    shortDesc: "Inicia los retinoides de forma segura y sin irritación",
    category: "ingredientes",
    level: "intermedio",
    price: 7.99,
    image: "/guides/retinoides-introduccion-segura.svg",
    fileUrl: "",
  },
  {
    title: "Péptidos y ceramidas: barrera cutánea",
    slug: "peptidos-ceramidas-barrera-cutanea",
    description: "Fortalece tu barrera cutánea con péptidos y ceramidas. Cómo funcionan, cuándo usarlos y cómo elegir los mejores productos para reparar tu piel.",
    shortDesc: "Fortalece y repara tu barrera cutánea",
    category: "ingredientes",
    level: "intermedio",
    price: 5.99,
    image: "/guides/peptidos-ceramidas-barrera-cutanea.svg",
    fileUrl: "",
  },
  {
    title: "Antioxidantes en skincare",
    slug: "antioxidantes-skincare",
    description: "Guía de los antioxidantes tópicos: vitamina C, E, ferúlico, resveratrol y más. Protege tu piel del daño ambiental y el envejecimiento prematuro.",
    shortDesc: "Protege tu piel del daño ambiental con antioxidantes",
    category: "ingredientes",
    level: "intermedio",
    price: 5.99,
    image: "/guides/antioxidantes-skincare.svg",
    fileUrl: "",
  },
  {
    title: "Cómo tratar manchas oscuras",
    slug: "como-tratar-manchas-oscuras",
    description: "Enfoque completo para la hiperpigmentación: ingredientes que funcionan, rutinas diarias, protección solar estricta y tratamientos profesionales.",
    shortDesc: "Rutina completa para reducir manchas y unificar el tono",
    category: "problemas-de-piel",
    level: "intermedio",
    price: 7.99,
    image: "/guides/como-tratar-manchas-oscuras.svg",
    fileUrl: "",
  },
  {
    title: "Guía de sérums por tipo de piel",
    slug: "guia-serums-tipo-piel",
    description: "Selecciona el sérum perfecto según tu tipo de piel y preocupaciones. Texturas, ingredientes clave y orden de aplicación explicados.",
    shortDesc: "Elige el sérum ideal para cada tipo de piel",
    category: "rutinas",
    level: "intermedio",
    price: 4.99,
    image: "/guides/guia-serums-tipo-piel.svg",
    fileUrl: "",
  },
  {
    title: "Aceites faciales: cuál elegir",
    slug: "aceites-faciales-cual-elegir",
    description: "Guía completa de aceites faciales no comedogénicos. Desde jojoba hasta escualano, aprende cuál es el mejor para tu tipo de piel.",
    shortDesc: "Los mejores aceites faciales para cada tipo de piel",
    category: "ingredientes",
    level: "intermedio",
    price: 4.99,
    image: "/guides/aceites-faciales-cual-elegir.svg",
    fileUrl: "",
  },
  {
    title: "Contorno de ojos: cuidados específicos",
    slug: "contorno-ojos-cuidados-especificos",
    description: "La delicada zona del contorno de ojos merece atención especial. Ingredientes, productos y técnicas para ojeras, bolsas y líneas de expresión.",
    shortDesc: "Cuidados específicos para la zona del contorno de ojos",
    category: "rutinas",
    level: "intermedio",
    price: 5.99,
    image: "/guides/contorno-ojos-cuidados-especificos.svg",
    fileUrl: "",
  },
  {
    title: "Cómo prevenir y tratar el acné",
    slug: "como-prevenir-tratar-acne",
    description: "Enfoque integral para el acné: ingredientes, rutinas, alimentación y cuándo buscar ayuda profesional para pieles propensas a brotes.",
    shortDesc: "Guía completa para prevenir y tratar brotes de acné",
    category: "problemas-de-piel",
    level: "intermedio",
    price: 6.99,
    image: "/guides/como-prevenir-tratar-acne.svg",
    fileUrl: "",
  },
  {
    title: "Exfoliación química vs física",
    slug: "exfoliacion-quimica-vs-fisica",
    description: "Diferencias entre exfoliación química y física, cuál elegir según tu piel, frecuencia recomendada y cómo evitar dañar tu barrera cutánea.",
    shortDesc: "Aprende las diferencias y elige la mejor exfoliación",
    category: "rutinas",
    level: "intermedio",
    price: 4.99,
    image: "/guides/exfoliacion-quimica-vs-fisica.svg",
    fileUrl: "",
  },

  // === 15 Avanzado ($9.99–$14.99) ===
  {
    title: "Retinoides: guía definitiva",
    slug: "retinoides-guia-definitiva",
    description: "Guía experta sobre retinoides: retinol, tretinoína, adapaleno, retinaldehído. Mecanismos de acción, protocolos avanzados y manejo de efectos secundarios.",
    shortDesc: "Guía experta de retinoides para resultados profesionales",
    category: "ingredientes",
    level: "avanzado",
    price: 11.99,
    image: "/guides/retinoides-guia-definitiva.svg",
    fileUrl: "",
  },
  {
    title: "Peeling químicos en casa",
    slug: "peeling-quimicos-en-casa",
    description: "Protocolos seguros para realizar peelings químicos en casa. Ácidos, concentraciones, tiempos de exposición y cuidados post-peeling.",
    shortDesc: "Protocolos seguros de peelings químicos para casa",
    category: "avanzado",
    level: "avanzado",
    price: 12.99,
    image: "/guides/peeling-quimicos-en-casa.svg",
    fileUrl: "",
  },
  {
    title: "Microbiota de la piel",
    slug: "microbiota-de-la-piel",
    description: "Cómo cuidar el microbioma cutáneo para una piel saludable. Probióticos, prebióticos y postbióticos en skincare explicados en profundidad.",
    shortDesc: "Cuida el ecosistema de tu piel con microbioma",
    category: "avanzado",
    level: "avanzado",
    price: 9.99,
    image: "/guides/microbiota-de-la-piel.svg",
    fileUrl: "",
  },
  {
    title: "Cómo tratar cicatrices de acné",
    slug: "como-tratar-cicatrices-acne",
    description: "Tratamiento avanzado para cicatrices de acné: ingredientes tópicos, procedimientos profesionales y rutinas específicas para cada tipo de cicatriz.",
    shortDesc: "Tratamientos avanzados para cicatrices de acné",
    category: "problemas-de-piel",
    level: "avanzado",
    price: 11.99,
    image: "/guides/como-tratar-cicatrices-acne.svg",
    fileUrl: "",
  },
  {
    title: "Skin cycling: la rutina avanzada",
    slug: "skin-cycling-rutina-avanzada",
    description: "El método de rotación de activos para maximizar resultados sin irritación. Plan semanal detallado con exfoliación, retinol y recuperación.",
    shortDesc: "Rutina de rotación de activos para máxima eficacia",
    category: "rutinas",
    level: "avanzado",
    price: 9.99,
    image: "/guides/skin-cycling-rutina-avanzada.svg",
    fileUrl: "",
  },
  {
    title: "Guía completa de ácido glicólico",
    slug: "guia-completa-acido-glicolico",
    description: "El AHA más estudiado en detalle: concentraciones, pH, usos específicos para textura, manchas y signos de edad. Protocolos avanzados.",
    shortDesc: "Dominio completo del ácido glicólico para resultados visibles",
    category: "ingredientes",
    level: "avanzado",
    price: 10.99,
    image: "/guides/guia-completa-acido-glicolico.svg",
    fileUrl: "",
  },
  {
    title: "Ácido salicílico: usos avanzados",
    slug: "acido-salicilico-usos-avanzados",
    description: "El BHA por excelencia para piel grasa y con tendencia acneica. Usos avanzados, concentraciones, combinaciones y protocolos específicos.",
    shortDesc: "Usos avanzados del BHA para piel grasa y acné",
    category: "ingredientes",
    level: "avanzado",
    price: 9.99,
    image: "/guides/acido-salicilico-usos-avanzados.svg",
    fileUrl: "",
  },
  {
    title: "Cómo combatir la flacidez facial",
    slug: "como-combatir-flacidez-facial",
    description: "Estrategias avanzadas para mejorar la firmeza y elasticidad de la piel. Ingredientes reafirmantes, masajes faciales y tecnologías no invasivas.",
    shortDesc: "Ingredientes y técnicas para mejorar la firmeza facial",
    category: "avanzado",
    level: "avanzado",
    price: 11.99,
    image: "/guides/como-combatir-flacidez-facial.svg",
    fileUrl: "",
  },
  {
    title: "Tratamiento de hiperpigmentación",
    slug: "tratamiento-hiperpigmentacion",
    description: "Protocolos avanzados para tratar melasma, manchas solares y PIH. Combinaciones de activos, procedimientos y prevención a largo plazo.",
    shortDesc: "Protocolos avanzados contra todo tipo de manchas",
    category: "problemas-de-piel",
    level: "avanzado",
    price: 12.99,
    image: "/guides/tratamiento-hiperpigmentacion.svg",
    fileUrl: "",
  },
  {
    title: "Cómo usar múltiples activos sin irritar",
    slug: "multiples-activos-sin-irritar",
    description: "Estrategias para combinar múltiples ingredientes activos de forma segura. Tablas de compatibilidad, horarios y señales de advertencia.",
    shortDesc: "Combina activos de forma segura maximizando resultados",
    category: "avanzado",
    level: "avanzado",
    price: 10.99,
    image: "/guides/multiples-activos-sin-irritar.svg",
    fileUrl: "",
  },
  {
    title: "Guía de pH y formulación",
    slug: "guia-ph-formulacion",
    description: "Entiende el pH de tu piel y cómo los productos afectan tu barrera cutánea. Guía de formulación básica para entender concentraciones y vehículos.",
    shortDesc: "El pH de la piel y la formulación de productos explicados",
    category: "avanzado",
    level: "avanzado",
    price: 9.99,
    image: "/guides/guia-ph-formulacion.svg",
    fileUrl: "",
  },
  {
    title: "Cómo elegir tu protector solar ideal",
    slug: "como-elegir-protector-solar-ideal",
    description: "Guía avanzada de fotoprotección: filtros químicos vs físicos, protección UVA/UVB/azul, texturas y cómo asegurar la protección adecuada.",
    shortDesc: "Selecciona el protector solar perfecto para tu piel",
    category: "proteccion-solar",
    level: "avanzado",
    price: 9.99,
    image: "/guides/como-elegir-protector-solar-ideal.svg",
    fileUrl: "",
  },
  {
    title: "Guía de mascarillas faciales",
    slug: "guia-mascarillas-faciales",
    description: "Tipos de mascarillas, ingredientes clave y cómo usarlas según tu tipo de piel. Mascarillas de arcilla, hidrogel, noche y exfoliantes.",
    shortDesc: "Todo sobre mascarillas faciales para cada necesidad",
    category: "rutinas",
    level: "avanzado",
    price: 9.99,
    image: "/guides/guia-mascarillas-faciales.svg",
    fileUrl: "",
  },
  {
    title: "Cómo tratar la rosácea",
    slug: "como-tratar-rosacea",
    description: "Guía para pieles con rosácea: ingredientes calmantes, desencadenantes comunes, rutina recomendada y cuándo buscar tratamiento dermatológico.",
    shortDesc: "Rutina y cuidados específicos para piel con rosácea",
    category: "problemas-de-piel",
    level: "avanzado",
    price: 10.99,
    image: "/guides/como-tratar-rosacea.svg",
    fileUrl: "",
  },
  {
    title: "Barrera cutánea: cómo repararla",
    slug: "barrera-cutanea-como-repararla",
    description: "Identifica los signos de una barrera cutánea dañada y aprende a repararla con ingredientes específicos, rutina minimalist y hábitos saludables.",
    shortDesc: "Repara tu barrera cutánea con ingredientes y rutina",
    category: "avanzado",
    level: "avanzado",
    price: 9.99,
    image: "/guides/barrera-cutanea-como-repararla.svg",
    fileUrl: "",
  },

  // === 10 Experto ($14.99) ===
  {
    title: "Dermatología cosmética avanzada",
    slug: "dermatologia-cosmetica-avanzada",
    description: "Fundamentos de dermatología cosmética: estructura de la piel, mecanismos de penetración, vehículos de formulación y principios activos de prescripción.",
    shortDesc: "Fundamentos de dermatología cosmética para profesionales",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/dermatologia-cosmetica-avanzada.svg",
    fileUrl: "",
  },
  {
    title: "Prescripción de activos por fototipo",
    slug: "prescripcion-activos-fototipo",
    description: "Cómo adaptar los tratamientos según el fototipo de piel. Riesgos de hiperpigmentación, selección de activos y protocolos personalizados por etnia.",
    shortDesc: "Activos y protocolos personalizados según fototipo",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/prescripcion-activos-fototipo.svg",
    fileUrl: "",
  },
  {
    title: "Protocolos de tratamiento avanzados",
    slug: "protocolos-tratamiento-avanzados",
    description: "Protocolos detallados para condiciones específicas: melasma resistente, acné quístico, envejecimiento severo y cicatrices profundas.",
    shortDesc: "Protocolos especializados para condiciones complejas",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/protocolos-tratamiento-avanzados.svg",
    fileUrl: "",
  },
  {
    title: "Guía completa de ácido tranexámico",
    slug: "guia-completa-acido-tranexamico",
    description: "El activo más prometedor para hiperpigmentación resistente. Mecanismo de acción, concentraciones, combinaciones sinérgicas y resultados clínicos.",
    shortDesc: "Activo avanzado para hiperpigmentación resistente",
    category: "ingredientes",
    level: "experto",
    price: 14.99,
    image: "/guides/guia-completa-acido-tranexamico.svg",
    fileUrl: "",
  },
  {
    title: "Cómo diseñar protocolos profesionales",
    slug: "disenar-protocolos-profesionales",
    description: "Metodología para diseñar protocolos de tratamiento personalizados: evaluación, selección de activos, timeline de resultados y ajustes según respuesta.",
    shortDesc: "Diseña planes de tratamiento personalizados efectivos",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/disenar-protocolos-profesionales.svg",
    fileUrl: "",
  },
  {
    title: "Fitoterapia aplicada al skincare",
    slug: "fitoterapia-aplicada-skincare",
    description: "Principios activos botánicos con evidencia científica: extractos, aceites esenciales y compuestos vegetales para el cuidado de la piel.",
    shortDesc: "Activos botánicos con respaldo científico para la piel",
    category: "ingredientes",
    level: "experto",
    price: 14.99,
    image: "/guides/fitoterapia-aplicada-skincare.svg",
    fileUrl: "",
  },
  {
    title: "Guía avanzada de protección solar",
    slug: "guia-avanzada-proteccion-solar",
    description: "Fotoprotección a nivel experto: espectro completo, filtros emergentes, fotodaño acumulativo, reparación del ADN y fotoenvejecimiento.",
    shortDesc: "Fotoprotección experta: espectro, filtros y reparación del ADN",
    category: "proteccion-solar",
    level: "experto",
    price: 14.99,
    image: "/guides/guia-avanzada-proteccion-solar.svg",
    fileUrl: "",
  },
  {
    title: "Cómo tratar melasma y manchas resistentes",
    slug: "tratar-melasma-manchas-resistentes",
    description: "Enfoque multiterapéutico para el melasma: combinación de activos tópicos, procedimientos en consultorio y manejo de expectativas realistas.",
    shortDesc: "Estrategias avanzadas para melasma y manchas difíciles",
    category: "problemas-de-piel",
    level: "experto",
    price: 14.99,
    image: "/guides/tratar-melasma-manchas-resistentes.svg",
    fileUrl: "",
  },
  {
    title: "Estrategias de rejuvenecimiento facial",
    slug: "estrategias-rejuvenecimiento-facial",
    description: "Rejuvenecimiento facial integral: desde ingredientes tópicos hasta tecnologías no invasivas. Planes según edad, grado de flacidez y presupuesto.",
    shortDesc: "Estrategias integrales de rejuvenecimiento no invasivo",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/estrategias-rejuvenecimiento-facial.svg",
    fileUrl: "",
  },
  {
    title: "Guía completa de láser y luz pulsada",
    slug: "guia-completa-laser-luz-pulsada",
    description: "Fundamentos de láser y luz pulsada intensa para la piel. Indicaciones, contraindicaciones, cuidados pre y post tratamiento y combinación con tópicos.",
    shortDesc: "Fundamentos de tecnologías láser para tratamiento facial",
    category: "avanzado",
    level: "experto",
    price: 14.99,
    image: "/guides/guia-completa-laser-luz-pulsada.svg",
    fileUrl: "",
  },
]

async function main() {
  console.log("🌱 Seeding 50 guides...")
  for (const guide of guides) {
    guide.fileUrl = `/guides/${guide.slug}.pdf`
    await prisma.digitalProduct.upsert({
      where: { slug: guide.slug },
      create: guide,
      update: guide,
    })
  }
  const count = await prisma.digitalProduct.count()
  console.log(`✅ ${count} guías disponibles`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
